#!/usr/bin/python
import sys
import os
import asyncio
import time
from aiogoogletrans import Translator

Todo = '/'.join([os.path.dirname(os.path.realpath(__file__)), 'Todo_list'])


def touch(fname, times=None):

    with open(fname, 'a'):
        os.utime(fname, times)


def gen_counter():
    c = 0
    while True:
        c += 1
        yield c


def get_todo():

    c = gen_counter()
    with open(Todo, 'r') as todo:
        txt = ''
        lst = {}
        for l in todo:
            t, p = l.split(',')
            p = int(p.strip())

            if(not p in lst.keys()):
                lst[p] = []
            lst[p].append([t, p])

        for k in reversed(sorted(lst.keys())):
            for i in lst[k]:
                t, p = i
                txt += '{}{:<5}{:<50}{:>0}\n'.format('#', next(c), t, p)

        print(txt)

       # print(lst)
        # print(txt)


def del_todo(line):

    f = open(Todo, 'r').readlines()
    with open(Todo, 'w') as todo:
        todo.writelines(f[:line-1]+f[line:])
    get_todo()


def save_todo(todo, prio):

    with open(Todo, 'a') as t:
        t.write(','.join([str(todo), str(prio)]) + '\n')

    get_todo()


if __name__ == "__main__":

    touch(Todo)

    args = sys.argv
    args.pop(0)

    if(args):
        print('{}{:<5}{:<50}{:>0}'.format('-', 'num', 'TODO', 'prio'))
    else:
        print('{}{:<5}{:<50}{:<0}'.format('-', 'num', 'TODO', 'prio'))
        get_todo()

    for arg in args:
        if(arg.startswith('#')):
            arg = arg.strip('#')
            del_todo(int(list(arg).pop(0)))
            break
        elif arg.startswith('!remove_all'):
            os.remove(Todo)
            print('cleared todos')
            break
        else:
            arg = arg.split(',')
            if(len(arg) == 1):
                t = arg[0]
                p = 0
            elif(len(arg) == 2):
                t, p = arg
    
        save_todo(t, p)
